### ISSUE TITLE
can not download pre-existing cache: 403 Forbidden

### ISSUE THREAD

**Issue by peterfind** [dzryk/antarctic-captions#3]
Hello!
Thanks for your sharing!

When I tried to download the pre-existing cache, there was a "ERROR 403: Forbidden".
The full log is:

> $ wget -m -np -c -U "eye02" -w 2 -R "index.html*" "https://the-eye.eu/public/AI/models/antarctic-captions/postcache.npy"
--2021-07-31 22:41:22--  https://the-eye.eu/public/AI/models/antarctic-captions/postcache.npy
Resolving the-eye.eu (the-eye.eu)... 162.213.130.242
Connecting to the-eye.eu (the-eye.eu)|162.213.130.242|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-07-31 22:41:23 ERROR 403: Forbidden.

I see there are some files in https://the-eye.eu/public/AI/models/antarctic-captions/
But I cannot download them from my web browser (windows 10) either.
including:
> -epoch=05-vloss=2.163.ckpt
antarctic-captions_repo.tar
postcache.npy
postcache.txt
readme.txt

Can you put the files in [baidu netdisk](https://pan.baidu.com/pcloud/home) (better for me to download) or Google drive?

Thanks for your great work and sharing!

**Comment by dzryk** [comment]
Hello,

Do these links work for you:
https://drive.google.com/file/d/1m789Ybtu0l_xMEVlx5cLy978obFMH1Vd/view?usp=sharing
https://drive.google.com/file/d/1gkZEEZfHNciC7n8SC1awtcdUzDeecJyx/view?usp=sharing

**Comment by peterfind** [comment]
Thanks for your reply!

Yes, the two links on google drive work for me, and I successfully download from them.

Can you also put the file `-epoch=05-vloss=2.163.ckpt` on google drive? It will be a great help to me.

Thanks again for your great work and timely response!

**Comment by dzryk** [comment]
Here is the ckpt:
https://drive.google.com/file/d/1fRKn4VEC3Cu9PMUIBW3ekywmVf46a6xN/view?usp=sharing
